package agent

import (
	"bytes"
	"context"
	"errors"
	"image"
	"image/color"
	"image/png"
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"testing"
)

func TestPrepareInputImagesSkipsOrdinaryDownloadFailures(t *testing.T) {
	// Keep the fixture generated by the standard library so the test exercises
	// the same format validation used for real attachments.
	imageData := testPNGBytes(t)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/missing":
			http.Error(w, "expired", http.StatusGone)
		case "/image":
			w.Header().Set("Content-Type", "image/png")
			_, _ = w.Write(imageData)
		default:
			http.NotFound(w, r)
		}
	}))
	defer server.Close()

	input := &Input{Text: "看图", ImageURLs: []string{server.URL + "/missing", server.URL + "/image"}}
	service := &Service{httpClient: server.Client()}
	if err := service.prepareInputImages(context.Background(), input); err != nil {
		t.Fatal(err)
	}
	if input.skippedImages != 1 {
		t.Fatalf("skipped images=%d, want 1", input.skippedImages)
	}
	if len(input.skippedImageErrors) != 1 || !strings.Contains(input.skippedImageErrors[0], "HTTP 410") {
		t.Fatalf("skip reasons=%#v", input.skippedImageErrors)
	}
	if len(input.ImageURLs) != 1 || input.ImageURLs[0] != server.URL+"/image" || len(input.imageDataURLs) != 1 {
		t.Fatalf("prepared images URLs=%#v data=%d", input.ImageURLs, len(input.imageDataURLs))
	}
}

func TestPrepareInputImagesKeepsHardInputFailures(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Length", strconv.FormatInt(maxImageDownloadBytes+1, 10))
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	input := &Input{Text: "看图", ImageURLs: []string{server.URL + "/too-large"}}
	service := &Service{httpClient: server.Client()}
	err := service.prepareInputImages(context.Background(), input)
	var inputErr *imageInputError
	if !errors.As(err, &inputErr) {
		t.Fatalf("hard image failure=%v, want image input error", err)
	}
	if input.skippedImages != 0 {
		t.Fatalf("hard failure was counted as skipped=%d", input.skippedImages)
	}
}

func TestPrepareInputImagesPreservesCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	input := &Input{Text: "看图", ImageURLs: []string{"https://example.invalid/image.png"}}
	err := (&Service{}).prepareInputImages(ctx, input)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("canceled image preparation=%v, want context.Canceled", err)
	}
	if input.skippedImages != 0 {
		t.Fatalf("canceled image was counted as skipped=%d", input.skippedImages)
	}
}

func TestSafeImageSkipReasonDoesNotExposeURLOrTransportDetails(t *testing.T) {
	err := errors.New(`图片下载失败：Get "https://cdn.example/image.png?token=private": connection reset`)
	got := safeImageSkipReason(err)
	if got != "图片下载失败" || strings.Contains(got, "private") || strings.Contains(got, "cdn.example") {
		t.Fatalf("unsafe skip reason=%q", got)
	}
}

func testPNGBytes(t *testing.T) []byte {
	t.Helper()
	var buffer bytes.Buffer
	fixture := image.NewRGBA(image.Rect(0, 0, 2, 2))
	fixture.Set(0, 0, color.RGBA{R: 20, G: 40, B: 60, A: 255})
	if err := png.Encode(&buffer, fixture); err != nil {
		t.Fatal(err)
	}
	return buffer.Bytes()
}
